const mongoose = require('mongoose')
const slugify = require('slugify')

// A "slug" is a URL-friendly version of a string. 
// It's typically used in web development to create readable and SEO-friendly URLs for a website's pages or resources. 
// A slug is generated by taking a string (such as the name of a resource) 
// and converting it into a format that can be used in a URL without causing any issues.


// To give another example, let's say we have a bootcamp with the name "Learn Python". 
// The slug for this bootcamp might be "learn-python". 
// This slug can be used in the URL to access the bootcamp's page, resulting in a URL like this: https://example.com/bootcamps/learn-python.


const BootcampSchema = new mongoose.Schema({

    name: {
        type: String,
        required: [true, 'please add a name'],
        unique: true,
        trim: true,
        maxlength: [50, 'Name cannot be more than 50 characters']
    },
    slug: String,
    description: {
        type: String,
        required: [true, 'please add a description'],
        unique: true,
        trim: true,
        maxlength: [500, 'description cannot be more than 50 characters']
    },
    website: String,
    phone: {
        type: String,
        maxlength: [20, 'Phone Number can not be more than 20 characters']
    },

    email: {
        type: String,
        match: [
            /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
            'Please add a valid email'
        ]
    },

    address: {
        type: String,
        required: [ true, 'Please add an address']
    },
    // location: {
    //     //GeoJSON Point
    //     type : {
    //         type: String,
    //         enum: ['Point'],
    //         required: true
    //     },
    //     coordiantes: {
    //         type: [Number],
    //         required: true,
    //         index: '2dsphere'
    //     },
    //     formattedAddress: String,
    //     street: String,
    //     city: String,
    //     state: String,
    //     zipcode: String,
    //     country: String, 
    // },

    careers: {
        type: [String],
        required: true,
        enum: [
            "Web Development",
            "Mobile Development",
            "UI/UX",
            "Data Science",
            "Business",
            "Other"
        ]
    },

    averageRating: {
        type: Number,
        min:[1,"Rating must be at least 1"],
        max: [10, "Rating must be under 10"]
    },

    averageCost: Number,

    photo: {
        type: String,
        default: 'no-photo.jpeg'
    },

    housing:{
        type: Boolean,
        default: false
    },
    jobAssistance:{
        type: Boolean,
        default: false
    },
    jobGurantee:{
        type: Boolean,
        default: false
    },
    acceptGi:{
        type: Boolean,
        default: false
    },
    createdAt:{
        type: Date,
        default: Date.now
    }
    
})


//create bootcamp slug from the name
BootcampSchema.pre('save',function(next){
    this.slug = slugify(this.name,{lower: true})
    next()
})


module.exports = mongoose.model('Bootcamp',BootcampSchema)